# MARKETING DATA

# How age influences the total amount spent in products at the store.

In [1]:
# Importing packages

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
%matplotlib inline
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
from pylab import *
import  statsmodels.api as sm
import statsmodels.stats.api as sms
from scipy.stats import boxcox
from datetime import datetime, date

from scipy import stats
from scipy.stats import ttest_ind
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Importing Dataset

In [4]:
Marketing = pd.read_excel("C:/Users/gabby/Downloads/marketing_campaign 2.xlsx")

In [5]:
Marketing.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-04-09 00:00:00,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-08-03 00:00:00,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-10-02 00:00:00,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [6]:
# Data Wrangling

In [7]:
Marketing2 = Marketing[['Year_Birth','Dt_Customer','Education','Marital_Status','Kidhome','Teenhome','MntWines','MntFruits','MntMeatProducts','MntFishProducts','MntSweetProducts','MntGoldProds','NumDealsPurchases','NumWebVisitsMonth','NumWebPurchases','NumCatalogPurchases','NumStorePurchases']]

In [8]:
Marketing2.head()

,Year_Birth,Dt_Customer,Education,Marital_Status,Kidhome,Teenhome,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebVisitsMonth,NumWebPurchases,NumCatalogPurchases,NumStorePurchases
0,1957,2012-04-09 00:00:00,Graduation,Single,0,0,635,88,546,172,88,88,3,7,8,10,4
1,1954,2014-08-03 00:00:00,Graduation,Single,1,1,11,1,6,2,1,6,2,5,1,1,2
2,1965,21-08-2013,Graduation,Together,0,0,426,49,127,111,21,42,1,4,8,2,10
3,1984,2014-10-02 00:00:00,Graduation,Together,1,0,11,4,20,10,3,5,2,6,2,0,4
4,1981,19-01-2014,PhD,Married,1,0,173,43,118,46,27,15,5,5,5,3,6

In [13]:
# Creating a new column for age.

In [9]:
Marketing2['Year_Birth'] = pd.to_datetime(Marketing2['Year_Birth'], format ='%Y')
Marketing2['Dt_Customer'] = pd.to_datetime(Marketing2['Dt_Customer'])

In [10]:
Marketing2["Dt_Customer"].dt.year.min() , Marketing2["Dt_Customer"].dt.year.max()

(2012, 2014)

In [11]:
Marketing2['CustomerAge'] = (Marketing2["Dt_Customer"].dt.year.max()) - (Marketing2['Year_Birth'].dt.year)

In [12]:
Marketing2.head()

,Year_Birth,Dt_Customer,Education,Marital_Status,Kidhome,Teenhome,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebVisitsMonth,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,CustomerAge
0,1957-01-01,2012-04-09,Graduation,Single,0,0,635,88,546,172,88,88,3,7,8,10,4,57
1,1954-01-01,2014-08-03,Graduation,Single,1,1,11,1,6,2,1,6,2,5,1,1,2,60
2,1965-01-01,2013-08-21,Graduation,Together,0,0,426,49,127,111,21,42,1,4,8,2,10,49
3,1984-01-01,2014-10-02,Graduation,Together,1,0,11,4,20,10,3,5,2,6,2,0,4,30
4,1981-01-01,2014-01-19,PhD,Married,1,0,173,43,118,46,27,15,5,5,5,3,6,33

In [14]:
# Data Exploration

In [15]:
Marketing2.Education.value_counts()

Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: Education, dtype: int64

In [16]:
Marketing2.Marital_Status.value_counts()

Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: Marital_Status, dtype: int64

In [17]:
# Clustering some columns

In [18]:
Marketing2['Couple']= Marketing2['Marital_Status'].replace({'Married':'Yes', 'Together':'Yes', 'Absurd':'No', 'Widow':'No', 'YOLO':'No', 'Divorced':'No', 'Single':'No','Alone':'No'})

In [19]:
Marketing2['LvlEducation']=Marketing2['Education'].replace({'Basic':'Basic','2n Cycle':'2n Cycle', 'Graduation':'Graduate', 'Master':'Postgraduate', 'PhD':'Postgraduate'})

In [20]:
Marketing2["Children"] = Marketing2["Kidhome"] +  Marketing2["Teenhome"]

In [21]:
Marketing2.head()

,Year_Birth,Dt_Customer,Education,Marital_Status,Kidhome,Teenhome,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,MntGoldProds,NumDealsPurchases,NumWebVisitsMonth,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,CustomerAge,Couple,LvlEducation,Children
0,1957-01-01,2012-04-09,Graduation,Single,0,0,635,88,546,172,...,88,3,7,8,10,4,57,No,Graduate,0
1,1954-01-01,2014-08-03,Graduation,Single,1,1,11,1,6,2,...,6,2,5,1,1,2,60,No,Graduate,2
2,1965-01-01,2013-08-21,Graduation,Together,0,0,426,49,127,111,...,42,1,4,8,2,10,49,Yes,Graduate,0
3,1984-01-01,2014-10-02,Graduation,Together,1,0,11,4,20,10,...,5,2,6,2,0,4,30,Yes,Graduate,1
4,1981-01-01,2014-01-19,PhD,Married,1,0,173,43,118,46,...,15,5,5,5,3,6,33,Yes,Postgraduate,1

In [22]:
Marketing3 = Marketing2[['CustomerAge','Couple','LvlEducation','Children','MntWines','MntFruits','MntMeatProducts','MntFishProducts','MntSweetProducts','MntGoldProds']]

In [23]:
Marketing3.head()

,CustomerAge,Couple,LvlEducation,Children,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds
0,57,No,Graduate,0,635,88,546,172,88,88
1,60,No,Graduate,2,11,1,6,2,1,6
2,49,Yes,Graduate,0,426,49,127,111,21,42
3,30,Yes,Graduate,1,11,4,20,10,3,5
4,33,Yes,Postgraduate,1,173,43,118,46,27,15

In [24]:
Marketing3.CustomerAge.value_counts()

38     89
43     87
39     83
42     79
36     77
44     77
41     74
49     74
45     71
40     69
58     55
56     53
35     53
62     52
37     52
46     51
55     51
48     50
60     50
59     49
54     49
32     45
51     45
47     44
52     44
57     43
63     43
31     42
28     42
50     42
34     39
33     39
30     38
53     36
61     35
29     32
25     30
65     30
64     29
26     29
27     27
66     21
24     18
68     16
67     16
23     15
22     13
69      8
71      7
70      7
21      5
19      5
20      3
18      2
115     1
73      1
121     1
114     1
74      1
Name: CustomerAge, dtype: int64

In [27]:
Marketing3.CustomerAge.describe()

count    2240.000000
mean       45.194196
std        11.984069
min        18.000000
25%        37.000000
50%        44.000000
75%        55.000000
max       121.000000
Name: CustomerAge, dtype: float64

In [ ]:
# Creating age range

In [28]:
Marketing3['AgeRange'] = pd.cut(x = Marketing3['CustomerAge'], bins = [18,25,45,60,121],
                         labels = ['18+','Adult','MiddleAge','Senior'])

In [29]:
Marketing3.head()

,CustomerAge,Couple,LvlEducation,Children,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,AgeRange
0,57,No,Graduate,0,635,88,546,172,88,88,MiddleAge
1,60,No,Graduate,2,11,1,6,2,1,6,MiddleAge
2,49,Yes,Graduate,0,426,49,127,111,21,42,MiddleAge
3,30,Yes,Graduate,1,11,4,20,10,3,5,Adult
4,33,Yes,Postgraduate,1,173,43,118,46,27,15,Adult

In [31]:
Marketing3['TotalMntSpent'] = Marketing3['MntWines'] + Marketing3['MntFruits'] + Marketing3['MntMeatProducts'] + Marketing3['MntFishProducts'] + Marketing3['MntSweetProducts'] + Marketing3['MntGoldProds']

In [32]:
Marketing4=Marketing3[['AgeRange','Couple','LvlEducation','MntWines','MntFruits','MntMeatProducts','MntFishProducts','MntSweetProducts','MntGoldProds','TotalMntSpent']]

In [33]:
Marketing4.head()

,AgeRange,Couple,LvlEducation,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,TotalMntSpent
0,MiddleAge,No,Graduate,635,88,546,172,88,88,1617
1,MiddleAge,No,Graduate,11,1,6,2,1,6,27
2,MiddleAge,Yes,Graduate,426,49,127,111,21,42,776
3,Adult,Yes,Graduate,11,4,20,10,3,5,53
4,Adult,Yes,Postgraduate,173,43,118,46,27,15,422

In [35]:
Marketing5 = Marketing4.groupby(['AgeRange','LvlEducation','Couple'])

In [36]:
Marketing5.first()

                               MntWines  MntFruits  MntMeatProducts  \
AgeRange  LvlEducation Couple
18+       2n Cycle     No         605.0       91.0            399.0
                       Yes          2.0        2.0             11.0
          Basic        No           0.0        0.0              1.0
                       Yes         16.0       36.0             21.0
          Graduate     No         490.0       44.0            125.0
                       Yes         36.0        2.0             42.0
          Postgraduate No           8.0        4.0             10.0
                       Yes        466.0       22.0            432.0
Adult     2n Cycle     No           4.0       17.0             19.0
                       Yes          6.0        3.0             14.0
          Basic        No           0.0        1.0              3.0
                       Yes          6.0       16.0             11.0
          Graduate     No         235.0       65.0            164.0
                       Yes         11.0        4.0             20.0
          Postgraduate No         712.0       26.0            538.0
                       Yes        173.0       43.0            118.0
MiddleAge 2n Cycle     No          53.0        1.0              5.0
                       Yes         12.0        5.0             25.0
          Basic        No           6.0       12.0              3.0
                       Yes          1.0        9.0              7.0
          Graduate     No         635.0       88.0            546.0
                       Yes        426.0       49.0            127.0
          Postgraduate No          81.0       11.0             50.0
                       Yes        520.0       42.0             98.0
Senior    2n Cycle     No          15.0        6.0              8.0
                       Yes        207.0       26.0            447.0
          Basic        No           NaN        NaN              NaN
                       Yes          2.0        0.0              7.0
          Graduate     No          48.0        5.0             48.0
                       Yes         84.0        5.0             38.0
          Postgraduate No         233.0        2.0             53.0
                       Yes         28.0        0.0              6.0

                               MntFishProducts  MntSweetProducts  \
AgeRange  LvlEducation Couple
18+       2n Cycle     No                  0.0              45.0
                       Yes                10.0               6.0
          Basic        No                  8.0               3.0
                       Yes                20.0              62.0
          Graduate     No                 29.0              20.0
                       Yes                20.0              21.0
          Postgraduate No                  2.0               2.0
                       Yes               147.0             113.0
Adult     2n Cycle     No                 30.0              24.0
                       Yes                15.0               7.0
          Basic        No                 10.0               6.0
                       Yes                11.0               1.0
          Graduate     No                 50.0              49.0
                       Yes                10.0               3.0
          Postgraduate No                 69.0              13.0
                       Yes                46.0              27.0
MiddleAge 2n Cycle     No                  2.0               1.0
                       Yes                 0.0               9.0
          Basic        No                 21.0               6.0
                       Yes                 2.0              14.0
          Graduate     No                172.0              88.0
                       Yes               111.0              21.0
          Postgraduate No                  3.0               2.0
                       Yes                 0.0              42.0
Senior    2n Cycle     No                  7.0               4.0
                       Yes                75.0               0.0
          Basic        No                  NaN               NaN
                       Yes                 3.0               7.0
          Graduate     No                  6.0              10.0
                       Yes               150.0              12.0
          Postgraduate No                  3.0               5.0
                       Yes                 1.0               1.0

                               MntGoldProds  TotalMntSpent
AgeRange  LvlEducation Couple
18+       2n Cycle     No             205.0         1345.0
                       Yes             12.0           43.0
          Basic        No               2.0           14.0
                       Yes            108.0          263.0
          Graduate     No              22.0          730.0
                       Yes             10.0          131.0
          Postgraduate No               4.0           30.0
                       Yes            102.0         1282.0
Adult     2n Cycle     No              39.0          133.0
                       Yes             36.0           81.0
          Basic        No               9.0           29.0
                       Yes             16.0           61.0
          Graduate     No              27.0          590.0
                       Yes              5.0           53.0
          Postgraduate No              80.0         1438.0
                       Yes             15.0          422.0
MiddleAge 2n Cycle     No              10.0           72.0
                       Yes             30.0           81.0
          Basic        No              40.0           88.0
                       Yes             10.0           43.0
          Graduate     No              88.0         1617.0
                       Yes             42.0          776.0
          Postgraduate No              39.0          186.0
                       Yes             14.0          716.0
Senior    2n Cycle     No              25.0           65.0
                       Yes            223.0          978.0
          Basic        No               NaN            NaN
                       Yes             10.0           29.0
          Graduate     No               7.0          124.0
                       Yes             28.0          317.0
          Postgraduate No              14.0          310.0
                       Yes             13.0           49.0

In [37]:
# Correlation Matrix

In [41]:
Marketing5.corr(method='pearson').style.format("{:.2}").background_gradient(cmap=plt.get_cmap('Blues'), axis=1)

In [ ]:
# Customer 18+ (18-24) with a basic level of education wether in a relationship or no tend to spend the most in products as well adults (25-44
# with a basic level of education and in a relationship. as well senior (65-121) with a basic level of education in a relationship.

In [39]:
Marketing6 = Marketing4.groupby(['AgeRange'])

In [42]:
Marketing6.corr(method='pearson').style.format("{:.2}").background_gradient(cmap=plt.get_cmap('Blues'), axis=1)

In [ ]:
# Customer between the age 18-24 are most likely to spend more money in wines and meat products.